# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 557d856eee43f1dc81a5eb4f08063b18bc682528d50c10809243c99b154259ec95cc81df2550ad88a1e3f80897f6cb23f620a7284bc73823d6fbe9de19d430d6

test:
  secret_key_base: 8104068900ff315953df31cb3500935a23dc3a47f0e98b94ebea454fd96346e5dd872e83627ffd37d4f7bd23e0d9dbee8ef018abb0fe8065fcd2398422821ae8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
